package compiler

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/xoai/sage-wiki/internal/config"
	"github.com/xoai/sage-wiki/internal/manifest"
)

const wikiIndexGeneratedNotice = "<!-- Generated by sage-wiki. Do not edit manually. -->"

// IndexIntroFilename is the optional project-level Markdown preamble embedded
// into the generated wiki/index.md before navigation sections.
const IndexIntroFilename = "index_intro.md"

type wikiIndexLink struct {
	label  string
	target string
}

// GenerateWikiIndex writes the deterministic entry point for compiled wiki artifacts.
func GenerateWikiIndex(projectDir string, cfg *config.Config, mf *manifest.Manifest, purpose Purpose) error {
	if cfg == nil {
		return fmt.Errorf("generate wiki index: nil config")
	}
	if mf == nil {
		return fmt.Errorf("generate wiki index: nil manifest")
	}

	outputDir := filepath.Join(projectDir, filepath.FromSlash(cfg.Output))
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("generate wiki index: create output directory: %w", err)
	}

	concepts, err := wikiIndexConceptLinks(projectDir, outputDir, mf)
	if err != nil {
		return err
	}
	summaries, err := wikiIndexSummaryLinks(projectDir, outputDir, mf)
	if err != nil {
		return err
	}

	title := cfg.Project
	if title == "" {
		title = "Wiki"
	}

	var content strings.Builder
	fmt.Fprintf(&content, "# %s\n\n%s\n\n", title, wikiIndexGeneratedNotice)
	intro, err := LoadIndexIntro(projectDir)
	if err != nil {
		return fmt.Errorf("generate wiki index: %w", err)
	}
	if intro != "" {
		content.WriteString(intro)
		content.WriteString("\n\n")
	}
	if purpose.Enabled() {
		purposeTarget, err := filepath.Rel(outputDir, filepath.Join(projectDir, PurposeFilename))
		if err != nil {
			return fmt.Errorf("generate wiki index: resolve purpose link: %w", err)
		}
		fmt.Fprintf(&content, "## Purpose\n\n[Read the wiki purpose](%s).\n\n", filepath.ToSlash(purposeTarget))
	}

	content.WriteString("## Concepts\n\n")
	writeWikiIndexLinks(&content, concepts, "_No compiled concepts._")
	content.WriteString("\n## Source summaries\n\n")
	writeWikiIndexLinks(&content, summaries, "_No compiled summaries._")

	indexPath := filepath.Join(outputDir, "index.md")
	if err := writeWikiIndexAtomic(indexPath, []byte(content.String())); err != nil {
		return fmt.Errorf("generate wiki index: write index: %w", err)
	}
	return nil
}

// LoadIndexIntro reads the optional human-maintained index preamble.
func LoadIndexIntro(projectDir string) (string, error) {
	data, err := os.ReadFile(filepath.Join(projectDir, IndexIntroFilename))
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("load index intro: %w", err)
	}
	return strings.TrimSpace(string(data)), nil
}

func wikiIndexConceptLinks(projectDir, outputDir string, mf *manifest.Manifest) ([]wikiIndexLink, error) {
	links := make([]wikiIndexLink, 0, len(mf.Concepts))
	for name, concept := range mf.Concepts {
		target, exists, err := wikiIndexArtifactTarget(projectDir, outputDir, concept.ArticlePath)
		if err != nil {
			return nil, fmt.Errorf("generate wiki index: inspect concept %q: %w", name, err)
		}
		if !exists {
			continue
		}
		links = append(links, wikiIndexLink{
			label:  formatConceptName(name),
			target: target,
		})
	}

	sort.Slice(links, func(i, j int) bool {
		if links[i].label != links[j].label {
			return links[i].label < links[j].label
		}
		return links[i].target < links[j].target
	})
	return links, nil
}

func wikiIndexSummaryLinks(projectDir, outputDir string, mf *manifest.Manifest) ([]wikiIndexLink, error) {
	links := make([]wikiIndexLink, 0, len(mf.Sources))
	for sourcePath, source := range mf.Sources {
		target, exists, err := wikiIndexArtifactTarget(projectDir, outputDir, source.SummaryPath)
		if err != nil {
			return nil, fmt.Errorf("generate wiki index: inspect summary for %q: %w", sourcePath, err)
		}
		if !exists {
			continue
		}
		links = append(links, wikiIndexLink{label: sourcePath, target: target})
	}

	sort.Slice(links, func(i, j int) bool {
		if links[i].label != links[j].label {
			return links[i].label < links[j].label
		}
		return links[i].target < links[j].target
	})
	return links, nil
}

func wikiIndexArtifactTarget(projectDir, outputDir, artifactPath string) (string, bool, error) {
	if artifactPath == "" {
		return "", false, nil
	}

	artifactPath = filepath.FromSlash(artifactPath)
	absPath := artifactPath
	if !filepath.IsAbs(absPath) {
		absPath = filepath.Join(projectDir, absPath)
	}
	info, err := os.Stat(absPath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", false, nil
		}
		return "", false, err
	}
	if info.IsDir() {
		return "", false, nil
	}

	target, err := filepath.Rel(outputDir, absPath)
	if err != nil {
		return "", false, err
	}
	return filepath.ToSlash(target), true, nil
}

func writeWikiIndexLinks(content *strings.Builder, links []wikiIndexLink, emptyText string) {
	if len(links) == 0 {
		content.WriteString(emptyText)
		content.WriteString("\n")
		return
	}
	for _, link := range links {
		fmt.Fprintf(content, "- [%s](%s)\n", link.label, link.target)
	}
}

func writeWikiIndexAtomic(path string, data []byte) error {
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, data) {
		return nil
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), ".index-*.tmp")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, path); err == nil {
		return nil
	}
	// Windows cannot replace an existing file with os.Rename.
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return os.Rename(tmpPath, path)
}
