package compiler

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/xoai/sage-wiki/internal/config"
	"github.com/xoai/sage-wiki/internal/manifest"
)

func TestGenerateWikiIndexPurposeAndSortedArtifacts(t *testing.T) {
	projectDir := t.TempDir()
	cfg := &config.Config{Project: "Research Wiki", Output: "compiled/wiki"}
	mf := manifest.New()

	writeWikiIndexFixture(t, projectDir, "compiled/wiki/concepts/zeta-topic.md")
	writeWikiIndexFixture(t, projectDir, "compiled/wiki/concepts/alpha-topic.md")
	writeWikiIndexFixture(t, projectDir, "compiled/wiki/summaries/zeta.md")
	writeWikiIndexFixture(t, projectDir, "compiled/wiki/summaries/alpha.md")

	mf.Concepts["zeta-topic"] = manifest.Concept{ArticlePath: "compiled/wiki/concepts/zeta-topic.md"}
	mf.Concepts["alpha-topic"] = manifest.Concept{ArticlePath: "compiled/wiki/concepts/alpha-topic.md"}
	mf.Concepts["missing-topic"] = manifest.Concept{ArticlePath: "compiled/wiki/concepts/missing-topic.md"}
	mf.Sources["sources/zeta.md"] = manifest.Source{SummaryPath: "compiled/wiki/summaries/zeta.md"}
	mf.Sources["sources/alpha.md"] = manifest.Source{SummaryPath: "compiled/wiki/summaries/alpha.md"}
	mf.Sources["sources/missing.md"] = manifest.Source{SummaryPath: "compiled/wiki/summaries/missing.md"}

	purpose := Purpose{Text: "Support research decisions.", Hash: "sha256:purpose"}
	if err := GenerateWikiIndex(projectDir, cfg, mf, purpose); err != nil {
		t.Fatalf("GenerateWikiIndex: %v", err)
	}

	got := readWikiIndex(t, projectDir, cfg.Output)
	want := `# Research Wiki

<!-- Generated by sage-wiki. Do not edit manually. -->

## Purpose

[Read the wiki purpose](../../purpose.md).

## Concepts

- [Alpha Topic](concepts/alpha-topic.md)
- [Zeta Topic](concepts/zeta-topic.md)

## Source summaries

- [sources/alpha.md](summaries/alpha.md)
- [sources/zeta.md](summaries/zeta.md)
`
	if got != want {
		t.Fatalf("unexpected index:\n%s\nwant:\n%s", got, want)
	}
	if strings.Contains(got, "missing") {
		t.Fatalf("missing artifacts must be omitted:\n%s", got)
	}
}

func TestGenerateWikiIndexIncludesProjectIntro(t *testing.T) {
	projectDir := t.TempDir()
	cfg := &config.Config{Project: "Project Wiki", Output: "wiki"}
	intro := "## What this is\n\nProject memory.\n\n## How to read\n\nStart here.\n"
	if err := os.WriteFile(filepath.Join(projectDir, IndexIntroFilename), []byte(intro), 0644); err != nil {
		t.Fatal(err)
	}

	if err := GenerateWikiIndex(projectDir, cfg, manifest.New(), Purpose{}); err != nil {
		t.Fatalf("GenerateWikiIndex: %v", err)
	}
	got := readWikiIndex(t, projectDir, cfg.Output)
	if !strings.Contains(got, "## What this is\n\nProject memory.\n\n## How to read\n\nStart here.\n\n## Concepts") {
		t.Fatalf("index intro missing or misplaced:\n%s", got)
	}
}

func TestGenerateWikiIndexWithoutPurposeUsesEmptySections(t *testing.T) {
	projectDir := t.TempDir()
	cfg := &config.Config{Output: "wiki"}

	if err := GenerateWikiIndex(projectDir, cfg, manifest.New(), Purpose{}); err != nil {
		t.Fatalf("GenerateWikiIndex: %v", err)
	}

	got := readWikiIndex(t, projectDir, cfg.Output)
	want := `# Wiki

<!-- Generated by sage-wiki. Do not edit manually. -->

## Concepts

_No compiled concepts._

## Source summaries

_No compiled summaries._
`
	if got != want {
		t.Fatalf("unexpected index:\n%s\nwant:\n%s", got, want)
	}
	if strings.Contains(got, "## Purpose") {
		t.Fatalf("disabled purpose must not add a section:\n%s", got)
	}
}

func TestGenerateWikiIndexIsIdempotent(t *testing.T) {
	projectDir := t.TempDir()
	cfg := &config.Config{Project: "Stable Wiki", Output: "wiki"}
	mf := manifest.New()
	writeWikiIndexFixture(t, projectDir, "wiki/concepts/stable-topic.md")
	mf.Concepts["stable-topic"] = manifest.Concept{ArticlePath: "wiki/concepts/stable-topic.md"}

	if err := GenerateWikiIndex(projectDir, cfg, mf, Purpose{}); err != nil {
		t.Fatalf("first GenerateWikiIndex: %v", err)
	}
	first := []byte(readWikiIndex(t, projectDir, cfg.Output))

	if err := GenerateWikiIndex(projectDir, cfg, mf, Purpose{}); err != nil {
		t.Fatalf("second GenerateWikiIndex: %v", err)
	}
	second := []byte(readWikiIndex(t, projectDir, cfg.Output))

	if string(first) != string(second) {
		t.Fatalf("repeated generation changed bytes:\nfirst:\n%s\nsecond:\n%s", first, second)
	}
}

func writeWikiIndexFixture(t *testing.T, projectDir, relativePath string) {
	t.Helper()
	path := filepath.Join(projectDir, filepath.FromSlash(relativePath))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("fixture"), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readWikiIndex(t *testing.T, projectDir, output string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(projectDir, filepath.FromSlash(output), "index.md"))
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
